
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer
)
from datetime import datetime
from zoneinfo import ZoneInfo
from reportlab.lib import colors
HEADER_COLOR = colors.HexColor("#1F4E79")
LIGHT_BLUE = colors.HexColor("#D9EAF7")
LIGHT_GREY = colors.HexColor("#F4F4F4")
SUCCESS = colors.HexColor("#2E8B57")
WARNING = colors.HexColor("#F4A300")
DANGER = colors.HexColor("#C62828")
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch
from datetime import datetime


def generate_report(
    filename,
    prediction,
    failure_risk,
    risk_level,
    defect,
    confidence,
    inputs,
    recommendations
):
    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER

    heading = styles["Heading2"]
    normal = styles["BodyText"]

    doc = SimpleDocTemplate(filename)

    story = []

    title_style.textColor = HEADER_COLOR
    story.append(
        Paragraph(
            "<b>AI-Based Thermoplastic Extrusion Quality Prediction Report</b>",
            title_style
        )
    )

    story.append(Spacer(1, 0.25 * inch))
    now = datetime.now(ZoneInfo("Asia/Kolkata"))

    story.append(
        Paragraph(
            f"<b>Date:</b> {now.strftime('%d-%m-%Y')}",
            normal
        )
    )

    story.append(
        Paragraph(
            f"<b>Time:</b> {now.strftime('%I:%M %p')}",
            normal
        )
    )

    story.append(Spacer(1, 0.25 * inch))

    story.append(
        Paragraph("Prediction Summary", heading)
    )

    summary = [
        ["Prediction", prediction],
        ["Failure Risk", f"{failure_risk:.2f}%"],
        ["Risk Level", risk_level],
        ["Likely Defect", defect],
        ["Confidence", f"{confidence:.2f}%"]
    ]

    table = Table(summary, colWidths=[180, 250])

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#D9EAF7")),
            ("GRID", (0,0), (-1,-1), 1, colors.grey),
            ("BOTTOMPADDING", (0,0), (-1,-1), 8),
            ("TOPPADDING", (0,0), (-1,-1), 8),
            ("FONTNAME", (0,0), (-1,-1), "Helvetica-Bold"),
            ("BACKGROUND", (0,0), (0,-1), colors.HexColor("#F5F5F5")),
        ])
    )

    if prediction == "PASS":
        table.setStyle(
            TableStyle([
                ("TEXTCOLOR", (1,0), (1,0), colors.green),
            ])
        )
    else:
        table.setStyle(
            TableStyle([
                ("TEXTCOLOR", (1,0), (1,0), colors.red),
            ])
        )

        if risk_level == "High Risk":
            table.setStyle(
                TableStyle([
                    ("TEXTCOLOR", (1,2), (1,2), colors.red),
                ])
            )
        elif risk_level == "Moderate Risk":
            table.setStyle(
                TableStyle([
                    ("TEXTCOLOR", (1,2), (1,2), colors.orange),
                ])
            )
        else:
            table.setStyle(
                TableStyle([
                    ("TEXTCOLOR", (1,2), (1,2), colors.green),
                ])
            )

    story.append(table)

    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph("Input Parameters", heading)
    )

    parameter_data = [["Parameter", "Value"]]

    for key, value in inputs.items():
        parameter_data.append([key, str(value)])

    table = Table(parameter_data, colWidths=[180, 250])

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0,0), (0,-1), LIGHT_GREY),
            ("BACKGROUND", (1,0), (1,-1), colors.white),
            ("GRID", (0,0), (-1,-1), 0.8, colors.grey),
            ("FONTNAME", (0,0), (-1,-1), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0,0), (-1,-1), 10),
            ("TOPPADDING", (0,0), (-1,-1), 10),
            ("VALIGN",(0,0),(-1,-1),"MIDDLE")
        ])
    )

    # ===== ADD STEP 4 HERE =====

    table.setStyle(TableStyle([
        ("TEXTCOLOR", (1,0), (1,0),
         SUCCESS if prediction == "PASS" else DANGER)
    ]))

    risk_color = {
        "Low Risk": SUCCESS,
        "Moderate Risk": WARNING,
        "High Risk": DANGER
    }.get(risk_level, colors.black)

    table.setStyle(TableStyle([
        ("TEXTCOLOR", (1,2), (1,2), risk_color)
    ]))

    # ===== END OF STEP 4 =====

    story.append(table)
    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph("AI Recommendations", heading)
    )

    if recommendations:
        for rec in recommendations:
            story.append(
                Paragraph(f"• {rec}", normal)
            )
    else:
        story.append(
            Paragraph(
                "No recommendations available.",
                normal
            )
        )

    story.append(Spacer(1, 0.3 * inch))

    story.append(
        Paragraph(
            "<b>Generated by:</b> AI-Based Thermoplastic Extrusion Quality Prediction System",
            normal
        )
    )

    doc.build(story)